config/routes.rb
Rails.application.routes.draw do
  get 'records/index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/notification.rb
class Notification < ApplicationRecord
  validates :title, :content, presence: true

  belongs_to :record
end

app/models/record.rb
class Record < ApplicationRecord
  validates :number, :court, :actor, :defendant, :summary, presence: true

  has_many :notifications, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  def index
    if params[:actor].present?
      @records = Record.where(actor: params[:actor])
    else
      @records = Record.all
    end
  end

  private

  def record_params
    params.require(:record).permit(:actor)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecordsCrawler</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/records/index.html.erb
<h2>Records</h2>

<h4>Search by actor:</h4>

<%= form_tag(records_index_url, method: :get) do %>
  <%= text_field_tag(:actor, params[:actor]) %>
  <%= submit_tag('Search') %>
<% end %>

<table style="width: 100%">
  <tr>
    <th>Number</th>
    <th>Court</th>
    <th>Actor</th>
    <th>Defendant</th>
    <th>Summary</th>
    <th>Notifications</th>
  </tr>
  <% @records.each do |record| %>
    <tr>
      <td><%= record.number %></td>
      <td><%= record.court %></td>
      <td><%= record.actor %></td>
      <td><%= record.defendant %></td>
      <td><%= record.summary %></td>
      <td><%= record.notifications.size %></td>
    </tr>
  <% end %>
  <% if @records.empty? %>
    <tr>
      <td colspan="6">No results were obtained.</td>
    </tr>
  <% end %>
</table>